version: '3'
services:
  node:
    build: .
    ports:
      - 3000:3000
    networks:
      - library-network
    depends_on:
      - db
    command: >
      sh -c "npm install && npx knex migrate:latest && npx knex seed:run && npm start"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library_management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:

networks:
  library-network:
    driver: bridge
